### ISSUE TITLE
Does the Member signup (AND Renewal!) still work?

### ISSUE THREAD

**Issue by williamkapke** [nodejs/board#39]
I just visited the signup link and it gave me an error... but then I went back and it said I was already a member. Which is true. 😃 

This evening I used the "Open Mic" time at the SFNode Meetup to promote people signing up and getting involved. I just want to make sure the system is still working.

This year we will have renewals for the first time- so does that work? Will some people (with signup timing just right) be able to vote just before their 1 year expires?

**Comment by ashleygwilliams** [comment]
cc/ @hackygolucky

**Comment by hackygolucky** [comment]
@williamkapke @ashleygwilliams We've adjusted the expiry codes for the coupons, so both the student and contributor codes should be working now ✨

**Comment by williamkapke** [comment]
@hackygolucky I'm unclear on what this means for this question:

> Will some people (with signup timing just right) be able to vote just before their 1 year expires?

**Comment by williamkapke** [comment]
What's the status? I'm hoping it is fixed and we can close this issue.

**Comment by hackygolucky** [comment]
@williamkapke It's a one year membership. It will expire at the year they signed up. Ballots are distributed January 20, so if folks signed up for membership prior to that, their memberships will expire before then and they'll need to renew.

**Comment by williamkapke** [comment]
We will be working on getting this system in better shape or even replaced by next November. I'll leave this open as a TODO.

**Comment by ljharb** [comment]
I got an email today and it's not worked well for me at all; I'm still unrenewed. I also expired on 1/27, but didn't get an email about it until today.

**Comment by fhemberger** [comment]
Same here.

**Comment by mcollina** [comment]
I got an email today, and it did not work for me as well :(. Same thing as @ljharb

**Comment by nebrius** [comment]
I got the email too. Following the instructions at https://github.com/nodejs/members/issues/1 worked for me.

**Comment by ljharb** [comment]
@nebrius I can't access that repo?

**Comment by yoannmoinet** [comment]
@nebrius same here, following the same instructions worked for me too.
Thank you for the reminder!

**Comment by nebrius** [comment]
@ljharb, yeah that repo is a private repo, and you have to be a member of @ nodejs/members to access it. I would have thought you were though, you're a member of the version management group, right?

**Comment by williamkapke** [comment]
I've informed the Board of this problem and hopefully we can get some relief for others that try in the future.

For now, please contact helpdesk@rt.linuxfoundation.org with your information (email used to signup is important)

**Comment by ljharb** [comment]
@nebrius i'm a member of the foundation (modulo renewal) and i have access to the version management repos, but i guess i don't have access to the "members" team

**Comment by williamkapke** [comment]
@nodejs/TSC or @nodejs/CTC -- Can someone please correct @ljharb's account please? Maybe there should be an audit to make sure all members are assigned to the correct group(s).

**Comment by Trott** [comment]
> @nodejs/tsc or @nodejs/ctc -- Can someone please correct @ljharb's account please? Maybe there should be an audit to make sure all members are assigned to the correct group(s).

Done. The members team has been manually maintained, I believe. So an audit will probably find lots of problems. /cc @mikeal just in case I'm mistaken.

**Comment by mikeal** [comment]
So, there's a question that we need to get an answer for: If someone is removed from the working groups/teams they had previously been involved with, should they be removed from members/org?

This has already happened a few times, certain people decide to leave groups they were working in and some time down the line we are confused as to why they are in the members team and the org because they aren't in an WG's.

Perhaps we should create an "alumni" team/repo. It's probably a good idea to encourage people to step away and take breaks to avoid burnout and keep themselves healthy.

**Comment by williamkapke** [comment]
What issues do we see with someone not being on any teams? This kinda seems like "Alumni" to me. Maybe they're schedule will change giving them more time and they join a group again; would we remove them from Alumni?

What purpose does the "members" team serve?
Could we just make it so that you get free membership if you are part of the GitHub org?

...these are not intended to be leading questions. I'm really not sure.

**Comment by ljharb** [comment]
fwiw my foundation membership (as opposed to my github org membership, which is fine) is still not renewed and the website still does not work properly. I emailed the help desk and after a short exchange, haven't heard back.

**Comment by mhdawson** [comment]
Sorry to ask a dump question, but were do I look for the codes for collaborators.  My membership expired a while ago and I wanted to renew.

**Comment by williamkapke** [comment]
@mhdawson Read here: https://github.com/nodejs/members/issues/1

LMK if it works or not.

**Comment by mhdawson** [comment]
Thanks, seemed to go through ok.

**Comment by Trott** [comment]
Closing stale issues and PRs as the repository is being archived.
